### ISSUE TITLE
Create samples

### ISSUE THREAD

**Issue by fire** [godlikepanos/anki-3d-engine#10]
Seeing how other game engines and frameworks use samples as a way to improve their engine. Anyone want to create samples using this engine?

Here are some samples:

* https://github.com/urho3d/Urho3D/tree/master/Source/Samples
* https://github.com/bkaradzic/bgfx/tree/master/examples
* The unreal engine community samples.

**Comment by godlikepanos** [comment]
I should be creating some samples but don't have much time. Someone else contributing samples won't be difficult at all (I hope).
