### ISSUE TITLE
a compile problem

### ISSUE THREAD

**Issue by guozhr** [godlikepanos/anki-3d-engine#113]
anki-3d-engine/ThirdParty/ImGui/../../AnKi/Util/Array.h:201:29: error: ‘is_same_v’ is not a member of ‘std’
  -> Array<std::enable_if_t<(std::is_same_v<TFirst, TRest> && ...), TFirst>, 1 + sizeof...(TRest)>;

when i do make, this problem come out,
my gcc version is 12.2
and i try to add cmake . -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_EXTENSIONS=OFF

how to fix it, very anxious !

**Comment by godlikepanos** [comment]
Hi,

Why do you build with `-DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_EXTENSIONS=OFF`? I've never used these flags.

**Comment by guozhr** [comment]
but now i have another problem: complie to 92%, it stop and have nothing message come out, looks finished!

**Comment by guozhr** [comment]
i built an android sample apk, install on my phone, it run and crash

**Comment by godlikepanos** [comment]
Can you check the logcat to find if there is an error somewhere? AnKi prints messages in logcat. Search for `AnKi`

**Comment by godlikepanos** [comment]
No more info, closing
