### ISSUE TITLE
Use appveyor for Windows CI

### ISSUE THREAD

**Issue by fire** [godlikepanos/anki-3d-engine#13]
I'll play around with getting appveyor to build with anki.

https://www.appveyor.com/

**Comment by godlikepanos** [comment]
That will be very useful!

**Comment by fire** [comment]
Have some initial results at https://ci.appveyor.com/project/fire/anki-3d-engine .

**Comment by fire** [comment]
I recommend we modify the cmake so it copies all the files needed for the sample and install it.

**Comment by fire** [comment]
It still doesn't start!

**Comment by godlikepanos** [comment]
Added appveyor. Will add more combinations along the way
