### ISSUE TITLE
do we have network and audio support?

### ISSUE THREAD

**Issue by kingofoz** [godlikepanos/anki-3d-engine#3]
I am newbie to anki3d, but I'd like to use it.

**Comment by godlikepanos** [comment]
Hi. I'm afraid that (at the moment) there is no support for network and audio. Audio is somewhat easy to add but networking is far for my expertise.

**Comment by kingofoz** [comment]
I see. does it have vulkan support now?

**Comment by godlikepanos** [comment]
Vulkan support is on its way. Hopefully in a few more months

**Comment by kingofoz** [comment]
keep going, buddy. looking forward to see the progress of the project.

**Comment by godlikepanos** [comment]
Thank you. I'll close the ticket now. For regular updates you can use https://twitter.com/anki3d
