### ISSUE TITLE
 compilation error#1

### ISSUE THREAD

**Issue by ksmk** [godlikepanos/anki-3d-engine#4]
clang-3.6.3 compilation error
Pipeline.h:154:14:
error: non-type template argument is not a constant expression
                Array<U64, m_shaders.getSize()> uuids;

note: implicit use of 'this' pointer is only allowed within the evaluation of a call to a 'constexpr' member function

**Comment by godlikepanos** [comment]
Thanks for the report. The fix is in 2a9e43ecc760936c35bdebc689d6efed36733f73
