### ISSUE TITLE
Physics engine choice

### ISSUE THREAD

**Issue by zettdaymond** [godlikepanos/anki-3d-engine#40]
Hello! I was wondering, why did you decide to switch from Newton to Bullet? In your old demo on youtube it seems that Newton worked just fine. Thanks.

**Comment by godlikepanos** [comment]
I think both libraries are great. Newton keeps adding lots of experimental half-finished features lately and that is causing some issues for AnKi.

**Comment by zettdaymond** [comment]
Ok. Thanks for the answer.
