### ISSUE TITLE
SSE4.2 assertion 

### ISSUE THREAD

**Issue by ksmk** [godlikepanos/anki-3d-engine#5]
there's a problem with SSE assertion ( clang-3.6, i7 gulftown)

App.cpp:178:6: error: use of
      undeclared identifier '__builtin_cpu_supports'
        if(!__builtin_cpu_supports("sse4.2"))
            ^
1 error generated.

**Comment by godlikepanos** [comment]
There is an assumption in AnKi that clang is GCC compatible. __builtin_cpu_supports is supported in clang 3.7. What I'll do is to bump the clang required version in the README.txt to 3.7.

Thanks for your report!
