### ISSUE TITLE
Do we have any development plan for Anki3D

### ISSUE THREAD

**Issue by kingofoz** [godlikepanos/anki-3d-engine#62]
Hi buddy,
After some search, I find this project. It looks amazing. Do you have any plan to support Android and iOS? I'd like to know if you have any plan for the engine.

Thanks.

**Comment by godlikepanos** [comment]
Hi there. Android and iOS is something that I would like to support but there are no immediate plans. The testing, s/w mentainance cost and the device costs are factors that make these platforms unattractive at the moment.

**Comment by kingofoz** [comment]
I see, thanks buddy. Do you have any game demos so I can have a look about the engine?

**Comment by godlikepanos** [comment]
If you build it there are 3 small demos to check out:
- simple_scene
- sponza
- physics_playground

The README.md provides some instructions on how to run those. Let me know if there is an issue

**Comment by kingofoz** [comment]
I see. Thanks buddy. I will try it.
