### ISSUE TITLE
- I am trying to install Anki 3D Engine to no avail -

### ISSUE THREAD

**Issue by Siegfried-Gottlich-Wotansson** [godlikepanos/anki-3d-engine#68]
### - First of all thank you for creating such an amazing free and open source engine as of what I can see rendered in your videos presenting it <<the World **needs** more people like you>> - ### 

So, I am trying to install it on a Windows 10 notebook. Soon enough when I am finished of this process I will thereafter install it in that notebook on a Linux Ubuntu OS. But there is a problem on the installation of it. I will ask of you to be patient with my ignorance over the matter... But what exactly is a the Anki 3D Engine "_checkout_" <<when you say it on README's installation on Windows alternative way of installing the Engine, that after opening Visual Studio, you say "checkout">>? The first way of installing the engine did not work, that is, through the PowerShell and after downloading and installing CMake, Vulkan and everything needed, including the environment variables - I may come back later to it if the other alternative does not function -; so let's first try to solve the other alternative that still may work on my Windows.

- Thank you for your attention!

**Comment by godlikepanos** [comment]
Hi,

Thanks for taking a look at AnKi. 

By "checkout" I mean the directory you've checked out (also known as cloned) the repository. In other words the directory where the README.md file is located. 

If you can also describe me the problem with the 1st method that would be great. Maybe I forgot a step or something.

**Comment by Siegfried-Gottlich-Wotansson** [comment]
> Hi,
> 
> Thanks for taking a look at AnKi.
> 
> By "checkout" I mean the directory you've checked out (also known as cloned) the repository. In other words the directory where the README.md file is located.
> 
> If you can also describe me the problem with the 1st method that would be great. Maybe I forgot a step or something.

Inside Visual Studio, after I selected the downloaded repository folder called "anki" <<through Ubuntu Terminal on Windows>>, it opened a window and there is no option or button function there called to "build" it... What do you mean with build it all up?

**Comment by Siegfried-Gottlich-Wotansson** [comment]
I don't want to be condescending with you, but rectified semiotics is VERY important to communicate precisely what you want... If you call a cellphone a tracker instead of a tracker, it is not really a cellphone even though you call by other name, is it? In other words, I am asking you to be didactic.

**Comment by godlikepanos** [comment]
Let's start over. If you want to build a AnKi on Windows **for Windows** using Visual Studio try these steps (I'll use visual studio 2019 as an example):

- Open visual studio
- In the 1st screen choose "open a local folder"
- Choose the location of AnKi and wait for visual studio to configure CMake
- In the main menu up top click Build -> Build all
- Wait for it to build
- Visual studio will drop everything in the `out` directory. Search for sponza.exe for example. In my case it was located in `out/build/x64-Release/bin/sponza.exe `
- Open powershell and navigate to the sponza sample. In my case `cd <path_to_anki>\samples\sponza`
- From there execute the sponza.exe. In my case `..\..\out\build\x64-Release\bin\sponza.exe`

Building such a project requires some prior knowledge of some terminology and understanding the tools involved. Happy to help if there is a problem but please come to me with a problem. Leave the truckers and their cellphones out.

**Comment by Siegfried-Gottlich-Wotansson** [comment]
> Let's start over. If you want to build a AnKi on Windows **for Windows** using Visual Studio try these steps (I'll use visual studio 2019 as an example):
> 
> * Open visual studio
> * In the 1st screen choose "open a local folder"
> * Choose the location of AnKi and wait for visual studio to configure CMake
> * In the main menu up top click Build -> Build all
> * Wait for it to build
> * Visual studio will drop everything in the `out` directory. Search for sponza.exe for example. In my case it was located in `out/build/x64-Release/bin/sponza.exe `
> * Open powershell and navigate to the sponza sample. In my case `cd <path_to_anki>\samples\sponza`
> * From there execute the sponza.exe. In my case `..\..\out\build\x64-Release\bin\sponza.exe`
> 
> Building such a project requires some prior knowledge of some terminology and understanding the tools involved. Happy to help if there is a problem but please come to me with a problem. Leave the truckers and their cellphones out.

- First step, done.
- Second step, done.
- Third step, done defectively. It doesn't work. I have downloaded Cmake, and in their site it says to download the binary and then unpack or unzip it in a folder. To access another binary dependent on it, you use a terminal that through the directory of Cmake and the dependant softwares directory it builds up the dependant software. After I open the Anki directory, Visual Studio just reproduces in itself those folders and nothing more; in other words, I don't see Cmake reacting or functioning and cannot build up the Anki Engine. Can you help me to clarify anything that I am doing wrong, or maybe do you want me to give you screenshots as well to describe the problem visually? The fact is that Visual Studio is not recognising it as a Cmake directory in my notebook.

**Comment by godlikepanos** [comment]
Visual studio is using its own CMake and doesn't interact with the one you've downloaded. Can you verify that your Visual Studio installation has the CMake component installed? https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019

**Comment by godlikepanos** [comment]
Closing. Feel free to reopen or continue the conversation.
