### ISSUE TITLE
Ubuntu18.04  has some issues

### ISSUE THREAD

**Issue by runner0353** [godlikepanos/anki-3d-engine#73]
./build/bin/sandbox 
[E][N/A ][7f2100cd8180] usage: ./build/bin/sandbox /path/to/config.xml relative/path/to/scene.lua (../sandbox/Main.cpp:31 init)
[E][N/A ][7f2100cd8180] Error reported. See previous messages (../sandbox/Main.cpp:275 main)

**Comment by godlikepanos** [comment]
Hi. The sandbox program is an internal tool and not something that should be used. You can try running the samples instead (see README.md)
