### ISSUE TITLE
Compiling errors when using anki-3d-engine

### ISSUE THREAD

**Issue by WilliamWangPeng** [godlikepanos/anki-3d-engine#79]
Dear authors
    Honor to write a letter to you here, I met one compiling error when using anki-3d-engine

![anki-3d-error](https://user-images.githubusercontent.com/51076736/110202747-aea9cf80-7ea5-11eb-88ac-ba24eb593652.png)

Do you know how to solve this

Thank you
Best Regards
William

**Comment by godlikepanos** [comment]
Hi William and thanks for the bug report. 

It seems your cmake version is lower than expected. AnKi requires cmake version 3.12 and newer (which I forgot to advertise in the master CMakeLists.txt, sorry). 

Getting a newer cmake will probably solve your issue.

**Comment by WilliamWangPeng** [comment]
> Hi William and thanks for the bug report.
> 
> It seems your cmake version is lower than expected. AnKi requires cmake version 3.12 and newer (which I forgot to advertise in the master CMakeLists.txt, sorry).
> 
> Getting a newer cmake will probably solve your issue.

Hi, dear expert, when I installed cmake 3.20, 
$ mkdir build
$ cd build
$ cmake ..
it can not show the Makefile, the errors are 
Building for linux
CMake error at CMakeLists.txt:179(if):
if given arguments:

"STREQUAL"  "RELEASE" 

Unknown arguments specified.

--configuring incomplete, errors occurred!

thank you
Best Regards
William
