### ISSUE TITLE
Black Screen on simple_scene

### ISSUE THREAD

**Issue by Goobley** [godlikepanos/anki-3d-engine#8]
Hi,

I'm just trying to run `simple_scene` on Linux Mint 17.2 with the AMD proprietary drivers and all I get is a black screen. No errors or anything, and then I press escape to close the scene.

Any suggestions as where to look for the problem? Cheers!

The log is as follows:

```
[I] Initializing application (version 0.1, build release Aug 29 2016, commit 0ff8816)... (/home/goobley/anki-3d-engine/src/anki/core/App.cpp:172 initInternal)
[I] Creating SDL window (/home/goobley/anki-3d-engine/src/anki/core/NativeWindowSdl.cpp:30 init)
[I] SDL window created (/home/goobley/anki-3d-engine/src/anki/core/NativeWindowSdl.cpp:87 init)
[I] Creating GL 4.5 context... (/home/goobley/anki-3d-engine/src/anki/gr/gl/GrManagerImplSdl.cpp:44 createContext)
[I] OpenGL async thread started: OpenGL version 4.5.13399 Core Profile Context 15.20.1013, GLSL version 4.40 (/home/goobley/anki-3d-engine/src/anki/gr/gl/RenderingThread.cpp:176 prepare)
[I] GPU vendor is UNKNOWN (/home/goobley/anki-3d-engine/src/anki/gr/gl/GlState.cpp:114 initRenderThread)
[I] Adding new data path "." (/home/goobley/anki-3d-engine/src/anki/resource/ResourceFilesystem.cpp:229 init)
[I] Adding new data path ".." (/home/goobley/anki-3d-engine/src/anki/resource/ResourceFilesystem.cpp:229 init)
[I] Initializing main renderer (/home/goobley/anki-3d-engine/src/anki/renderer/MainRenderer.cpp:46 create)
[I] Initializing offscreen renderer. Size 1280x768 (/home/goobley/anki-3d-engine/src/anki/renderer/Renderer.cpp:112 initInternal)
[I] Initializing IR (Image Reflections) (/home/goobley/anki-3d-engine/src/anki/renderer/Ir.cpp:70 init)
[W] File does not contain the requested compression (/home/goobley/anki-3d-engine/src/anki/resource/ImageLoader.cpp:395 loadAnkiTexture)
[I] Initializing SSAO. Size 320x192 (/home/goobley/anki-3d-engine/src/anki/renderer/Ssao.cpp:104 initInternal)
[W] File does not contain the requested compression (/home/goobley/anki-3d-engine/src/anki/resource/ImageLoader.cpp:395 loadAnkiTexture)
[I] Main renderer initialized. Rendering size 1280x768 (/home/goobley/anki-3d-engine/src/anki/renderer/MainRenderer.cpp:113 create)
[I] Initializing scripting engine... (/home/goobley/anki-3d-engine/src/anki/script/ScriptManager.cpp:29 init)
[I] Application initialized (/home/goobley/anki-3d-engine/src/anki/core/App.cpp:303 initInternal)
[I] Entering main loop (/home/goobley/anki-3d-engine/src/anki/core/App.cpp:359 mainLoop)
[I] Destroying scripting engine... (/home/goobley/anki-3d-engine/src/anki/script/ScriptManager.cpp:20 ~ScriptManager)
[I] Destroying main renderer (/home/goobley/anki-3d-engine/src/anki/renderer/MainRenderer.cpp:33 ~MainRenderer)
[I] Bye!! (/home/goobley/anki-3d-engine/samples/simple_scene/Main.cpp:157 main)
```

**Comment by Goobley** [comment]
Adding `config.set("dbg.enabled", true);` to the configuration draws a wireframe of geometry (see attached). So my guess is that those image loading warnings are the cause of the issue as the scene is untextured. I'll dig in more later.

Here's a picture of the output now:

![screenshot from 2016-08-29 13 09 07](https://cloud.githubusercontent.com/assets/9143392/18051047/242303e8-6dea-11e6-9918-089b41c0265e.png)

**Comment by godlikepanos** [comment]
Thanks for the report. I had tested the simple scene in a very old fglrx driver (the one that ships with ubuntu 14.04 or close to that version) some months ago. The output was mostly fine apart from some depth fighting. Maybe it's the same issue but amplified in your case. These warnings are fine. Need to turn them into regular info because it's misleading.

I'll try to fix that issue I was seeing and hopefully it will fix yours as well. Will drop a word here when I commit that.

In the meantime, which driver do you use? fglrx or amdgpu-pro?

**Comment by Goobley** [comment]
Thanks. I'm using fglrx-updates driver package. `Version 2:15.201-0ubuntu0.14.04.1`

Catalyst Control Centre gives the following info.
![screenshot from 2016-08-29 13 34 55](https://cloud.githubusercontent.com/assets/9143392/18051619/9088d7c6-6ded-11e6-8ce8-1cc60a8b20fe.png)

I'll see if I can test the open source drivers too later.

**Comment by godlikepanos** [comment]
If you test using the opensource drivers you might need to change the GL version to 4.3. That can be done from the config (<glminor>3</glminor>).

**Comment by godlikepanos** [comment]
I've tried the sample in my old fglrx setup and I didn't notice any issues including the one I remembered. Since fglrx is a deprecated driver version I don't think we should bother at this point. If you agree I'll close the ticket as "won't fix".

**Comment by Goobley** [comment]
That's fine. It makes sense. I've updated to more recent open source 
drivers and still can't run the demo because it requires some GL4.4 
stuff, which isn't available in those yet. My gpu isn't supported by 
amdgpupro. Is there any way to limit what the engine uses to make it 4.3 
compatible or do I need to rewrite the shaders in use or something?

Cheers!

**Comment by godlikepanos** [comment]
I think the only extension that is missing from Mesa at the moment and AnKi requires it is GL_ARB_query_buffer_object. I've started using that extension for lens flares 2 days ago. That's bad timing. The good thing though is that simple_scene won't use lens flares at the moment so it won't be triggered.

If you tell me where it's failing I can try to workaround the issue. 

A few questions:
- What GPU are you using?
- What distro are you using?
- If you are using ubuntu do you use latest mesa? Padoka PPA maybe?

Thanks in advacne

**Comment by godlikepanos** [comment]
I'll close this issue since it refers to an old AMD driver.

Thanks for the report!

**Comment by mcallegari** [comment]
I'm having the same issue on Kubuntu 16.04 and proprietary Nvidia drivers on a GeForce GTX 960M, which indeed supports OGL 4.5

Footnotes of README.md: 
- `$cd mkdir build` should be `$mkdir build`
- `NOTE: If you have a better way to build on Windows please let us know.`

I use [MSYS2](http://www.msys2.org/) and it's fantastic. Based on pacman package system, it feels like Linux on Windows :)

**Comment by godlikepanos** [comment]
@mcallegari Thanks for the report. It's indeed odd. What driver version do you have?

**Comment by mcallegari** [comment]
Sorry, I've edited the comment just now

**Comment by godlikepanos** [comment]
I've enable another test scene. Maybe that works. It's the well known sponza. You could try pulling the latest and re-build. The README has all the relevant instructions.

**Comment by mcallegari** [comment]
Just tried sponza. Unfortunately, no joy.
Still a black screen and it's also difficult to exit from it. It almost hangs the PC and I need to kill -9 the process
