### ISSUE TITLE
how to add this project as a subdirectory using CMake?

### ISSUE THREAD

**Issue by tree786** [godlikepanos/anki-3d-engine#85]
Apologiez if this is not quite related to anki, but i am having some troubles trying to use it as subdirectory in project. Here is my cmake file:

```
cmake_minimum_required(VERSION 3.11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_BUILD_TYPE "Release")

project(testing)

add_subdirectory(anki)

add_executable(binary main.cpp)

target_link_libraries(binary anki)
```

However when i try to compile a main.cpp (has the `#include <AnKi/AnKi.h>` header) , i get an error like this : 
```
fatal error: #include <AnKi/AnKi.h> No such file or directory
```
I am quite bad at the cmake, so not sure what i need to change in the CMakeLists file to correct this? Do i need to specify `include_directories` for all deps?
Here is my folder structure FYI: 
![Screenshot_2021-09-06_17-45-02](https://user-images.githubusercontent.com/40580296/132240853-93d6def4-ecb7-4496-81bb-4a785783ab4a.png)

**Comment by tree786** [comment]
sorry i have also found there is a 'Discussions' section, i should have probably posted this there instead of issues section ......

**Comment by godlikepanos** [comment]
Hi. Yes with cmake you need to set some include directories. The `include_directories` should do the trick. 

Please note that I haven't tried to do include the master CMakeLists.txt in another project like this. You might run into other issues.

**Comment by tree786** [comment]
Ok that fine, i think ill just use the original anki folder instead , as i find cmake dependencies very hard to resolve and link. I close issues for now
